version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0

  build:
    commands:
      - echo "Restoring dependencies..."
      - dotnet restore

      - echo "Building .NET Web API..."
      - dotnet build FortunaeLibraryManagementSystem/FortunaeLibraryManagementSystem.csproj --configuration Release

      - echo "Running tests..."
      - dotnet test --configuration Release --no-build

      - echo "Publishing application..."
      - dotnet publish FortunaeLibraryManagementSystem/FortunaeLibraryManagementSystem.csproj -c Release -o ./publish

  post_build:
    commands:
      - echo "Verifying build output..."
      - ls -l ./publish

      - echo "Adding Procfile to publish directory..."
      - echo "web: dotnet FortunaeLibraryManagementSystem.dll" > ./publish/Procfile

      - echo "Zipping deployment package..."
      - cd publish
      - zip -r ../app.zip .
      - cd ..

      - echo "Uploading artifact to AWS S3"

artifacts:
  files:
    - app.zip
  discard-paths: no