version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0

  build:
    commands:
      - echo "Restoring dependencies..."
      - dotnet restore

      - echo "Building .NET Web API..."
      - dotnet build FortunaeLibraryManagementSystem/FortunaeLibraryManagementSystem.csproj --configuration Release --no-restore

      - echo "Running tests..."
      - dotnet test --configuration Release --no-build --verbosity normal

      - echo "Publishing application as self-contained..."
      - dotnet publish FortunaeLibraryManagementSystem/FortunaeLibraryManagementSystem.csproj -c Release -r linux-x64 --self-contained true -p:PublishTrimmed=true -o ./publish

  post_build:
    commands:
      - echo "Verifying build output..."
      - ls -l ./publish

      - echo "Adding Procfile to publish directory..."
      - echo "web: ./publish/FortunaeLibraryManagementSystem" > ./publish/Procfile
      - ls -l ./publish

      - echo "Zipping deployment package..."
      - cd publish
      - zip -r ../app.zip .
      - cd ..

artifacts:
  files:
    - app.zip
  discard-paths: yes